### ISSUE TITLE
Rename modal files such as 'ModalEditAbout*.vue'

### ISSUE THREAD

**Issue by mattburnett-repo** [activist-org/activist#1066]
### Terms

- [X] I have searched all [open bug reports](https://github.com/activist-org/activist/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow activist's [Code of Conduct](.github/CODE_OF_CONDUCT.md)

### Behavior

File naming is unclear. Consider renaming files to something like 'ModalEditText*.vue'

**Comment by andrewtavis** [comment]
@YoSoyAlexElPine picked this up and #1068 was just merged, @mattburnett-repo :) Do you want to merge these changes into your current work so that we can pick it up more easily once we have the stores refactored?

Appreciate the help here, @YoSoyAlexElPine! Looking forward to working with you again :)

**Comment by andrewtavis** [comment]
Nice to have you in the community, @YoSoyAlexElPine :)
