### ISSUE TITLE
Unable to run app locally

### ISSUE THREAD

**Issue by TeddyGavi** [activist-org/activist#113]
### Terms

- [X] I have searched all [open bug reports](https://github.com/activist-org/activist/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

OS:
- Ubuntu 22.04

### Summary
- running `docker compose up` doesn't serve the app locally at host 3000

### Images
![Screenshot from 2023-05-04 10-40-22](https://user-images.githubusercontent.com/102203363/236517885-76bba5d0-f472-4190-9f94-f65a6f1ff69d.png)
![Screenshot from 2023-05-04 10-40-14](https://user-images.githubusercontent.com/102203363/236518032-c7b7dcae-0c7a-4a2e-9717-938d56402a22.png)

### Steps taken to reproduce:
- `forked` and `git clone` repository
- Installed `docker` and `docker compose` V2 
```bash
Docker Compose version v2.17.3
Docker version 23.0.5, build bc4487a
```
- `cd` into project directory
- run `docker compose up`
  - error results:
   ```  ERROR [5/6] RUN pip install -r requirements.txt ``` 
  - same error when I run `docker-compose up --build`

### Notes:
Asked for help in matrix
- @andrewtavis suggested deleting the line `pylint-django` in `requirements.txt`
- error results:
  - same as previous, referencing the line after `pylint-django` ie `gunicorn 20.1.0`
- removing this line yields no success. 

### Possible Cause?
FWIW, this is the line (seemingly) where the issue is:
```bash
#0 4.956 Collecting isort<6,>=4.2.5 (from pylint<3,>=2.0->pylint-django==2.5.3->-r requirements.txt (line 4))
#0 4.986   Downloading isort-5.12.0-py3-none-any.whl (91 kB)
#0 5.012      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.2/91.2 kB 3.6 MB/s eta 0:00:00
```
- nothing completes after that 
- following the Stack Trace I see that we are looking for: 
```bash
/usr/local/lib/python3.11/
```
  - I have `Python 3.10.6`

I would love to get this project up and running and start contributing! Its great what you are doing here. I am new to docker apologies if this is something obvious I don't mean to take away important time from your day. 

Regards,

**Comment by andrewtavis** [comment]
Thanks, @TeddyGavi! :) @wkyoshida, tagging you as I did in the element thread in case you have an idea 🙃

We’ll figure this out and get you up and running, @TeddyGavi! 🚀

**Comment by wkyoshida** [comment]
Hey all!

Not sure what this is yet :thinking: but some notes if they help:

- Regarding:
> following the Stack Trace I see that we are looking for:
> 
> `/usr/local/lib/python3.11/`

So this is due to the Docker image, [backend/Dockerfile](https://github.com/activist-org/activist/blob/9decb0061040c9825410c9dbd63545696e9d67f1/backend/Dockerfile#L1), that the `docker compose up` command is using to build the Docker container. The image comes with python `v3.11` already installed and is the version being used. This python is separate and shouldn't affect the one in the host machine, `Python 3.10.6` in this case.  

- I am also on Ubuntu, and I have run into issues with Docker actually when it's installed via the snap. I have it installed now from Docker itself instead of from the snap. Not sure if you got the snap version, @TeddyGavi, but could be something to look into (I've seen others around mentioning issues with the snap as well). FWIW I just installed [Docker Desktop](https://docs.docker.com/desktop/install/ubuntu/), which comes with a lot of the Docker toolset.
- From the images, it does look like the `pip install -r requirements.txt` command is failing to complete successfully. Not sure why yet. From the images, it does look like my local is trying to get the same versions for the Docker image and the Python packages. As a sanity check, @TeddyGavi, does the `pip install -r requirements.txt` command run fine if you were to run it in the `backend/` directory of the repo?

**Comment by andrewtavis** [comment]
Thanks @wkyoshida! 🙌

> FWIW I just installed [Docker Desktop](https://docs.docker.com/desktop/install/ubuntu/), which comes with a lot of the Docker toolset.

This is a good point 🤔 I guess we're not mentioning Docker Desktop in the setup documentation, which could be why you were confused when I was talking about deleting the container, @TeddyGavi. Would instructing people to also download that make sense? And when we can get this figured out let's definitely add some notes to the readme and contributing files about snap vs. downloading from Docker itself.

> As a sanity check, @TeddyGavi, does the pip install -r requirements.txt command run fine if you were to run it in the backend/ directory of the repo?

This is a great idea to check as well 😊 Thanks @wkyoshida!

**Comment by TeddyGavi** [comment]
Hello! Thank you @wkyoshida and @andrewtavis  for the detailed response. 

Regarding this: 

> This python is separate and shouldn't affect the one in the host machine

This makes total sense and I suppose I should've realized that! :thinking: *docker newbie*

Regarding this: 
> FWIW I just installed [Docker Desktop](https://docs.docker.com/desktop/install/ubuntu/), which comes with a lot of the Docker toolset.

That is indeed the path I took, ie without using snap (as a side note, snap is not my greatest friend... :cry: )

I just completed the following: 
- `cd` into `backend/`
- ran `pip install -r requirements.txt` which completed fine!
- ran `docker compose up` from project root and failed on `pip install --upgrade pip`
- `cd` into `backend/` and ran `pip install --upgrade pip`
- back to root and ran `docker compose up`
- failed with: 
- >failed to solve: failed to register layer: Error processing tar file(exit status 1): w
rite /usr/local/bin/node: no space left on device 
- *new tmux window* restarted docker `systemctl ...`
- *tmux window of project, at project root* ran `docker compose up`
- SUCCESS! :grinning:  project running :+1: 

![image](https://user-images.githubusercontent.com/102203363/236705568-ee8071f7-585c-41fb-a756-69c2e8641ba3.png)

I can also see the container and the images in the desktop client. So it would appear this is all good now? I have no idea why running the `pip` commands from the `backend/` made the difference?

Regarding this 
> ...definitely add some notes to the readme and contributing files about snap vs. downloading from Docker itself.

I would like to help work on this once the correct path is sorted out, as I have some first hand experience!

Thank you for much for the help! 

Onto actual project issues now :grinning: :rocket:

**Comment by wkyoshida** [comment]
Hey :wave: 

No worries! Glad to have helped!

> Would instructing people to also download that make sense? 

You don't need Docker Desktop necessarily to get docker itself running, but maybe a good idea to have a sidenote that Docker Desktop might be a good beginner-friendly option if unfamiliar with docker.  

> And when we can get this figured out let's definitely add some notes to the readme and contributing files about snap vs. downloading from Docker itself.

We could perhaps. I would say that it's maybe an issue that we would be more likely to see with a new contributor running Ubuntu again. I'm a little hesitant to start adding OS-specific notes, though. What we could do is add the Docker Desktop beginner-friendly note and leave it at that. If someone is already a docker user, I'm thinking it might be okay to assume they would already know the docker snap oddities. 

> ... (as a side note, snap is not my greatest friend... :cry: )

Same, my friend, same... :disappointed::laughing:  

> I have no idea why running the `pip` commands from the `backend/` made the difference?

Yeah, I'm thinking that wasn't what resolved it actually either. So the other error that you mentioned is interesting: 

`failed to solve: failed to register layer: Error processing tar file(exit status 1): write /usr/local/bin/node: no space left on device`

That error could suggest it's a docker disk space issue. Some common suggestions for resolving this are to:
- Do precisely what you did :laughing: which is likely why the issue seems resolved
- Remove the images and containers in the system to clear some space. Can be done by running `docker system prune`
- Or to configure docker with a larger disk space limit as in this [SO answer](https://stackoverflow.com/a/61469441) - could be a better long-term option
   - Maybe a good other sidenote to add along with the Docker Desktop one

Also - I just found the thread on matrix where you two were discussing before. You did mention the error there - oops! Wish I had seen it earlier.

----
Glad you got it working though! :rocket:

**Comment by andrewtavis** [comment]
Assigning to give credit where credit is due for some docker documentation we can turn to with similar issues, @wkyoshida :) And great that it’s up and running now, @TeddyGavi!! 🚀 I agree as well that an initial commit to the readme and contributing markdown files that references Docker Desktop for those new to Docker would be a great idea and a simple way to get @TeddyGavi his first commit :) :) Very much in line with activist being as beginner friendly as possible 🙃

Closing this now 🙌
