### ISSUE TITLE
Responsive footer 

### ISSUE THREAD

**Issue by to-sta** [activist-org/activist#244]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is about the footer of the website. On mobile the footer it takes up almost the full screen. 

![image](https://github.com/activist-org/activist/assets/49518857/e1fd1bbe-4d42-403c-885a-2ee6f92abab7)

To improve this, we can only display the social icon for small screen. 

### Contribution

I'll be working on this.

**Comment by andrewtavis** [comment]
Thanks, @to-sta! Marked the task as finished in the meeting notes 😊 [frontend/components/landing/LandingCommunityBanner.vue](https://github.com/activist-org/activist/blob/main/frontend/components/landing/LandingCommunityBanner.vue) is the component I mentioned that this could be based off of :) The [website footer component](https://github.com/activist-org/activist/blob/main/frontend/components/WebsiteFooter.vue) is a bit of a long mess (suggestions on that being cleaned up welcome!), but the section of that that you're looking to edit is the top of the file where it says `<!-- Note: Content Sections Top -->` up until `<!-- Note: Content Sections Left and Right -->` :)

**Comment by to-sta** [comment]
Thanks @andrewtavis for the links. I will jump into the code soon.  Just made a quick prototyp of the footer based on the websites source code in [codepen](https://codepen.io/to_sta/pen/BaGGVqr?editors=1010) in case you want to have a look. 

Would look like this on mobile:
![image](https://github.com/activist-org/activist/assets/49518857/6cb93cc6-3310-4b01-95ab-ee48671dcd79)

**Comment by andrewtavis** [comment]
Definitely an improvement, @to-sta! I went into the [designs](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=805%3A231&mode=design&t=wtLwem1DcuqNKDR8-1) just now and played around a bit. How does maintaining the `•` between words look to you between those menu options?

![Mode=Light, Mobile=True, Compressed=False, Apps=False](https://github.com/activist-org/activist/assets/24387426/d4f49a2e-76ea-43f0-be7f-ae511d57531e)

The spacing above is just an initial sketch 😊 We'd need to have a line break to make sure that the second line of options in `Resources` and `Organization` starts with a `•` rather than it being at the end of the line. How does this look to you?

**Comment by andrewtavis** [comment]
And also of course only implement the options that are within the current version, so no need for `Finances`, `Careers`, `Press` and the three dot social option that would be when we have more than we have these days (about to be one less with the platform formally known as Twitter likely being dropped as we haven't had the time to start using it and it's not looking like the place we want to be at all).

**Comment by to-sta** [comment]
I think the dots are good, then it looks uniform.

**Comment by andrewtavis** [comment]
Ok, great @to-sta! Feel free to send along a PR when you're ready, and let me know if you have any questions :)

**Comment by andrewtavis** [comment]
Closed via #248 🚀 Thanks @to-sta! 🙌
