### ISSUE TITLE
Create CardTextEntry component

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#271]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

A major component that's needed is one that provides a text box into which the user can type information. An example of this can be seen as the [About you card in the MVP designs](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=2461%3A5123&mode=design&t=hJRakNbmbK83mZ9P-1). In this component we need:

- A required `header` prop
- An optional `description` prop
- An optional `placeholder` prop
- A required `multiline` boolean prop
- A text box that can be expanded vertically above the `md` breakpoint and is scrollable below it
- Coloration and styling as dictated by the designs and [tailwind.config.ts](https://github.com/activist-org/activist/blob/main/frontend/tailwind.config.ts)

An example of this component (does not include a description below the header) is below:

![Description](https://github.com/activist-org/activist/assets/24387426/5e8af4a2-5052-48f2-beef-a06346242ec5)

### Contribution

Happy to work on this or help someone who has interest in working on it! :blush

**Comment by to-sta** [comment]
Would be happy to work on this issue

**Comment by to-sta** [comment]
I am almost done with this component. But i have two questions before i make the PR. 

1. What's the prop multiline used for? I can imagine either switching between <input> and <textarea> or set the textarea `row`  attribute.  

Here is an example of the textarea with `rows` based on the `multiline` prop.
```vue
<v-if multiline>
    <textarea :placeholder="placeholder" class="px-2 py-1 rounded-md bg-transparent border border-white dark:border-white resize-none md:resize-y overflow-y-scroll md:overflow-hidden"
    rows="5" cols="40"> </textarea>
</v-if>
<v-else>
    <textarea :placeholder="placeholder" class="px-2 py-1 rounded-md bg-transparent border border-white dark:border-white resize-none md:resize-y overflow-y-scroll md:overflow-hidden"
    rows="1" cols="40"> </textarea>
</v-else>
```

2. I was thinking about the max-length attribute for the `<textarea>` and that it should reflect the `max_length` set to the model in the backend. Otherwise if the max-length is exceeded it will throw an error. If we constraint the `max_length` in the frontend to the value in the backend dynamically, then this should not be an issue. I am not sure what's common practice in cases like this. 

Here is an example how we could retrieve the max_length from the backend.
```python
class MyModel(models.Model):
    title = models.CharField(max_length=200)

# retrieve the max_length
MyModel._meta.get_field('title').max_length
```

**Comment by andrewtavis** [comment]
Hey @to-sta! Thanks for the questions :)

> I can imagine either switching between and `<textarea>` or set the textarea `row` attribute.

I'm assuming the prior option was there was `<input>`? I was thinking that `input` would be used :) For in cases where `multiline` is true we'd have a `<textarea>` with say five rows for mobile and three for desktop - so below `md` it's five 🤔 How does this sound?

> If we constraint the max_length in the frontend to the value in the backend dynamically, then this should not be an issue. I am not sure what's common practice in cases like this.

This sounds like the correct path forward! Definitely link the two values, and have it be defined in the backend. Thanks for the initiative on this for getting things linked properly!

**Comment by to-sta** [comment]
I made the changes so that if `multiline` is `true` then its a `<textarea>` `else` its an `<input>` field. But i am not sure how to link the tailwind breakpoint to the html attribute `rows`. Any ideas? 

For the `maxlength` i would create a seperate issue if you do not mind. There are probably more inputs/textarea where this applies.

**Comment by andrewtavis** [comment]
Thanks for this, @to-sta! An idea to get the rows argument working would be to have two different `<textarea>` elements where one is `hidden` before the `md` breakpoint and the other is `block`. I'd say that the one beneath the `md` breakpoint can also not include an option to resize, whereas the one that's above would include this :)

**Comment by andrewtavis** [comment]
I'll leave them off the settings pages for now now that I think about it, @to-sta :) We might not be editing the event/org description from the settings anyway, or maybe we'll have both options so it's easy for people to edit it if they'd like to. Let me know what you think on this and I can send another commit to add them!

**Comment by to-sta** [comment]
I think both options are valid. Personally would expect general settings in the [id]/settings and i do not see the org/event description as general settings.

**Comment by andrewtavis** [comment]
Makes sense, @to-sta! Thanks for sharing your views on this :) :)
