### ISSUE TITLE
 Enforcing Standard Structure in Django Models

### ISSUE THREAD

**Issue by momanyisamuel** [activist-org/activist#293]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Maintaining a consistent and well-structured codebase is crucial for the maintainability and scalability of activist. In activist-org's Django backend, it's essential to ensure that the `models.py` files adhere to a standardized structure to enhance code readability and streamline future development efforts.

**Proposed Solution:**
To address this issue, I propose implementing a standard structure for the `models.py` files across activist-org's Django backend. By adhering to a consistent structure, we can minimize confusion, make it easier for developers to navigate the codebase, and promote best practices.

**Standard Structure Guidelines:**
Below is an example of the proposed standard structure for `models.py` files. This structure is meant to provide a clear and organized layout for defining Django models and is based on the following references

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Models

```

from django.db import models

class MyModel(models.Model):
    # Fields
    #Use UUID for id fields
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False) 
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField()

    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    #Metadata
    class Meta:
        verbose_name = "My Model"
        verbose_name_plural = "My Models"

    #Methods
    def __str__(self):
        return self.name

```
The task is to review and update existing `models.py` file  and ensure that it is in line to the proposed standard structure - other structure improvement suggestions are welcome. This may involve reorganizing code and adding missing fields or methods.

LATER - There is also need to create a style-guide to document the standards which will be a good reference for other developers

### Contribution

Happy to support someone on this issue or work on it myself

**Comment by to-sta** [comment]
I would like to work on this issue :)

**Comment by andrewtavis** [comment]
Finally a backend issue for you, @to-sta 😉 Assigning now :)

**Comment by to-sta** [comment]
I have question regarding this issue. Some models have a field `index` like below. 

```python
class OrganizationTopic(models.Model):
    index: models.IntegerField(null=True)
    org_id: models.ForeignKey(Organization, on_delete=models.CASCADE)
    topic_id: models.ForeignKey(Topic, on_delete=models.CASCADE)
```

Should that be replaced by the `id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False) ` or is this needed for something else? I am not sure since the index is not specified as the pk and because of that django will have an id and the index. 

I am also not familiar with assigning a field with `:` and could not find a explanation online. Could you tell me what's the difference?

Made migrations and checked one of the tables and saw that the only field there is the autogenerated pk. 
```sql
activist=# SELECT * FROM apps_topicformat;
 id 
----
(0 rows)
```

This can also be seen in the migrations file:
```python
    migrations.CreateModel(
        name="TopicFormat",
        fields=[
            (
                "id",
                models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name="ID",
                ),
            ),
        ],
    ),
```

**Besides that i am almost done** :smiley:

<ins>Additional:</ins>
Had to adjust the .env DATABASE_HOST value because i got an error with connection to the postgres database. I used the value "db". I encounted that issues myself a while ago and found this explanation:

> The way the containers know about each other is that, by default, compose will create a network and every container in the stack will join it. Then, the hostnames of each container are resolved to their service name.

The service name in the docker-compose.yml is "db".
```yml
db:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
```

**Comment by kurtisolo** [comment]
> UUIDField

Hi @to-sta

From what I understand, these models are just a draft, so you might just add a comment as a reminder that it's possible and advisable to standardize the models using 'UUIDField' for the 'index' fields.
Regarding the use of colons instead of the usual equals sign: I believe this is a syntax error, feel free to correct it in my opinion IMO.
To stay updated you can check [here](https://github.com/activist-org/activist/issues/174) regarding the development of the models.

**Comment by andrewtavis** [comment]
7e71c25 does some edits so that the models are now all ordered based on the four way split we're implementing in #174. I also removed all the unnecessary `id` fields as I realized that those were in there because in making the schemas we were just having "index" as a placeholder for the primary key, but those tables are just relational and don't need one.

Closing this now 😊 Thanks @to-sta and @momanyisamuel!

**Comment by to-sta** [comment]
@andrewtavis i like the changes 😄. Guess next time it would make sense for me to also check the [schema](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=5459%3A33844&mode=design&t=BkUoaTEN6bNZ9jkx-1).

Django will still create a primary key for each model, but the code base is leaner that way and maps one-to-one to Figma. 

From the [docs](https://docs.djangoproject.com/en/4.2/topics/db/models/#automatic-primary-key-fields):
> Each model requires exactly one field to have [primary_key=True](https://docs.djangoproject.com/en/4.0/ref/models/fields/#django.db.models.Field.primary_key) (either explicitly declared or automatically added).

**Comment by andrewtavis** [comment]
We can also declare it explicitly, @to-sta, but then I don’t really see the point as we won’t be using it ever :) A minor change to make down the road if it’s needed!

Realized my thanks for the issue left out @kurtisolo 🙃 Thanks as well for jumping into the discussion here! 😊
