### ISSUE TITLE
Close search result menu tooltip when clicking the button

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#634]
### Terms

- [X] I have searched all [open bug reports](https://github.com/activist-org/activist/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

After recent commits the functionality of [MenuSearchResult](https://github.com/activist-org/activist/blob/main/frontend/components/menu/MenuSearchResult.vue) is almost where it should be.  This functionality can be seen on the [home page](https://activist.org/home/). We have:

- The ability to open the tooltip by clicking the button
- The ability to close the tooltip by clicking outside of it (important for mobile)
- The ability to close the tooltip by moving the cursor away from the button and tooltip (important for desktop)

The issue is that the above conditions are conflicting and we actually can't close the tooltip by clicking the button again anymore (my assumption is that both the first and third options above fire and we just get it again).

Any support on this would be appreciated! Happy to help as well :)

**Comment by arescrimson** [comment]
Hi! I can work on this if you want :))

**Comment by andrewtavis** [comment]
Hey @arescrimson 👋 Thanks for your interest in activist and wanting to help! We'd be happy to get some support here! I'll assign you now, and please let me know if you have any questions!

**Comment by arescrimson** [comment]
So this is actually more tricky than I thought itd be: 

Basically, your assumption is correct: when I disable the onClickOutside function, you can then click on the menu itself and it will toggle and and off, as intended. However, it looks like the onClickOutside function is actually firing when you press on the menu item itself, which then results in showToolTip being toggled to false when menu is clicked(unintended) but then being toggled to opposite of showToolTip(true) by the menu(intended), which then results in the tooltip not closing because showToolTip is still true.

![image](https://github.com/activist-org/activist/assets/66581240/ee80f751-c389-4954-bd2e-af3e4bbceb07)

For now, I'm still not too sure, because it looks like onClickOutside is a Vue function, and I'm still unclear on why it is firing when I am clicking on the menu component itself. Currently I'm working on potentially adding another ref that toggles when the menu component itself is called, and then blocks the onClickOutside function from firing that way, but other ways are also welcome. If anyone has any ideas, let me know :)))

**Comment by andrewtavis** [comment]
Hey @arescrimson! Thanks for documenting and confirming all this :) Note on why `onClickOutside` is being triggered by the button: the ref for that is the tooltip itself not including the button, which is then recorded as being outside the bounds. Maybe a fix would be to have the ref for `onClickOutside` be a parent div or something that contains both the button and the tooltip?

**Comment by arescrimson** [comment]
That was one of the things I had also considered, but wasn't sure about whether it could be a viable solution. Good explanation, that makes this problem a lot clearer. Thank you! :D

**Comment by andrewtavis** [comment]
Very welcome, @arescrimson! Let me know how it goes and hoping for the best 🤞😊

**Comment by arescrimson** [comment]
After some more work, it looks like adding a parent div containing the ref to `onClickOutside` works, but I actually saw that simply assigning the div containing the button, icon and tooltip events with the ref of `onClickOutside`  solved the issue. 

That being said, I additionally added a `toggleTooltip` function for possible readability/debugging in the future, which replaces the former `showToolTip = !showToolTip` in the click property of the button. However, this can also be reverted; up to any more experienced peoples' call if they think this is a necessary change. 

![image](https://github.com/activist-org/activist/assets/66581240/6319fb2d-4203-4974-8169-51cff64ddc71)

Finally, I also removed the `onClickOutside` refs in the TooltipMenuSearchResult components, as the `onClickOutside` is now being handled by the parent div. If all of this sounds correct, I can go ahead and start that PR :D

**Comment by andrewtavis** [comment]
Sounds good and looking forward to the PR, @arescrimson! Really appreciate the dialog here :)

**Comment by andrewtavis** [comment]
Closed by #649 with a minor edit in 09ab4d7 🥳 Thanks @arescrimson! Really was nice working with you on this! By all means let us know if you'd like to work on something else, and we have the dev sync on Saturday if you'd like to join 😊 More details for that will be in the [dev channel on Matrix](https://matrix.to/#/!CRgLpGeOBNwxYCtqmK:matrix.org?via=matrix.org&via=utwente.io&via=matrix.pierre-couy.fr) shortly.

**Comment by arescrimson** [comment]
For sure!!! It was great working with you, and thank you for all the help! This was my first time working on any kind of open-source software and I'm really grateful for having the opportunity to contribute😁 For sure let me know if there's any other issues/topics you'd like me to tackle, and I'll definitely keep the dev sync in mind.
