### ISSUE TITLE
Make cursor pointer on map marker hover

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#684]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

In #680 we added a basic marker tooltip to the [MediaMap component](https://github.com/activist-org/activist/blob/main/frontend/components/media/MediaMap.vue). One thing that's missing is that the cursor doesn't turn into a pointer when we hover over the marker, so it's not clear that clicking will have any kind of effect.

Note that the events map can be found at [activist.org/events/123/about)](https://activist.org/events/123/about) :)

We use [MapLibre GL JS](https://github.com/maplibre/maplibre-gl-js) for our mapping service, so their documentation and code related to it or [MapBox](https://github.com/mapbox/mapbox-gl-js) that it was forked from would be where to look. The following is a great example, but is making a default element rather than using the default marker from MapLibre GL JS:

https://maplibre.org/maplibre-gl-js/docs/examples/set-popup/

If we want to make a custom marker such that we can change the cursor though, this would also be possible. The question is then where does the source image for this live :)

### Contribution

Happy to assist with this or work on it myself at some point!

**Comment by arescrimson** [comment]
This sounds like an interesting issue here, @andrewtavis. Would be open to looking further into it; noticed that there are a lot of new issues regarding the map features, and this would be a great place to start learning how it works 😄 

In addition, could you let me know where this is located? I definitely remember seeing a map component somewhere(possibly events?), but I couldn't find it.

**Comment by arescrimson** [comment]
Okay: on further investigation it just looks like the functionality for changing the cursor into a map interaction pointer(grab hand?) is already there - the problem is just actually getting it to change to an actual pointer once the marker is moused over. Interesting issue! Let me know if there's anything I can do to help 😁

**Comment by arescrimson** [comment]
Another thing, and let me know if I'm looking in the wrong place; in the actual deployed website, the map looks like this.

![image](https://github.com/activist-org/activist/assets/66581240/a1c00fb4-53b9-4550-bc29-4a8eb4407099)

With the development build, the map and marker look different, and it looks like the issue is resolved because the cursor does become a pointer on hover. 

![image](https://github.com/activist-org/activist/assets/66581240/27fb0886-c79b-4c98-8d49-0e0fcf52a0ee)

I looked a bit further, and it looks like you actually updated the map with #680, which should have updated the map in the deployed website. However, there is still the difference, is there something I'm overlooking?

**Comment by andrewtavis** [comment]
Will assign this one to you @arescrimson as you're doing some good investigations already and this. Where are you seeing the images that you're posting exactly? The one where there's a random black rectangle looks like a buggy controller, and the one where the marker is solid is the old version of the map that should only be on older forks 🤔

**Comment by andrewtavis** [comment]
I would be really happy to get some support with the map as there's lots to do :) Big thing is that for this I think we have to follow this example more directly;

https://maplibre.org/maplibre-gl-js/docs/examples/set-popup/

Right now we initialize just a base marker that doesn't allow us to set actions associated with a map element that has an id. The way they do it in the example with the Washington Monument makes sense to me, but the main hurdle is we need to figure our own image for the map that can hopefully take styling such that we can make it red and blue for action and learn events. 

Once this one works out, I think moving on to for the clusters would make sense 😊

**Comment by arescrimson** [comment]
In regards to what I was confused about, it was because the version that I saw(the outdated map) had the correct functionality of cursor updating to a pointer. However, I was unsure since I'm working off an up to date main branch, yet when I run the development frontend, this outdated map shows up instead of the map on the live website. 

Also because I noticed that your most recent commit updating the map functionality included updated information for the marker popup, which is reflected in the outdated map, yet not reflected in the live site. Sorry if I'm overlooking something, just want to make sure if it's a problem on my end 😅

**Comment by andrewtavis** [comment]
I think you need to pull the most recent changes into your local dev then :) If you have any references to `Leaflet` locally, then that's a sign that you still have the old map. This is what I'm seeing live atm:

![Screenshot_2024-02-03 13 34 37](https://github.com/activist-org/activist/assets/24387426/eab95233-aa25-41b7-a578-2497e45ca1b3)

That's Chrome on Mac, and it's similarly reflected on mobile Safari - with dark mode being fine for mobile. And looking a bit more closely at the first screenshot, what I thought was a wrong control's just a street 🛣️😅 But are you cutting off the rest of the controls and the attribution in your screenshot. That's what's confusing me :)

**Comment by arescrimson** [comment]
You're right 😅 forgot to merge the latest changes into local dev, which was why I was seeing the previous map. Seeing the correct version now, and I'll get to working on it. 
![image](https://github.com/activist-org/activist/assets/66581240/612e8b93-ed33-4579-a00a-db0724a5c528)

Also wanted to ask about these error messages within `MediaMap`. 
![image](https://github.com/activist-org/activist/assets/66581240/6ce498e9-1d4d-4f40-a7f7-f163693b05e1)

Everything seems to be working fine, which leads me to suspect that there might be a types issue instead of the module not being found? Ran yarn install and postinstall, but it still persists. Let me know if I'm missing anything that generates the types, etc 😄

**Comment by andrewtavis** [comment]
Hey there @arescrimson :) How's all with this issue here? Let me know if there's anything I can do to support! Happy to jump on another call here at some point as well if that could help 😊

**Comment by arescrimson** [comment]
Yeah for sure @andrewtavis! I actually got caught up in some events and was unable to work on this, but my spring break is also coming up for this and next week. Would love to schedule a talk just to catch up and talk about the project and this issue. Let me know how you want to schedule that, since I'll definitely be able to have time to work on this in the near future 😁

**Comment by andrewtavis** [comment]
Maybe this Sunday, @arescrimson? :)

**Comment by arescrimson** [comment]
Sure! I can do anytime after 12PM PST. Let me know if that works for you, and where we're meeting 😄

**Comment by andrewtavis** [comment]
Sounds good, @arescrimson! Maybe we can do 1pm so it's not crazy late for me, but I'd also be done with dinner by then :)

**Comment by nkoehring** [comment]
Just for clarification: the ticket is to make it look like this:
![image](https://github.com/activist-org/activist/assets/246402/e9041a28-346e-4c1d-a160-db3d6ecced6c)

Instead of this:
![image](https://github.com/activist-org/activist/assets/246402/583212bc-366c-4e03-8494-ccacff2c3e87)

Right?

**Comment by andrewtavis** [comment]
Closed via #759 🥳 Thanks for jumping in for the fix, @nkoehring! Really a lot more simple than how I'd been explaining to @arescrimson. 

@arescrimson, hope the merge on this was alright with you :) Let's still do that call so that we can figure out the next issue for you. There's still tons of work that needs to be done on the map, or also some of the share modal options could be something we could similarly look into 😊
