### ISSUE TITLE
Address some style issues

### ISSUE THREAD

**Issue by lucianmurmurache** [activist-org/activist#752]
### Terms

- [X] I have searched all [open bug reports](https://github.com/activist-org/activist/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

A few inconsistencies, for example, the right sidebar is overlapped by the navigation menu.
The use of `relative` and `sticky` in the same line.
"This page is currently under development" message does not look right on sm & md  screens

![Screenshot 2024-03-08 122704](https://github.com/activist-org/activist/assets/48526455/016c7f63-c208-444b-a595-0e1ce727b462)
![Screenshot 2024-03-08 122733](https://github.com/activist-org/activist/assets/48526455/df518d4f-2e90-44f4-8adf-e4249f2483e8)
![Screenshot 2024-03-08 122803](https://github.com/activist-org/activist/assets/48526455/45b8df50-427b-484e-8dee-b65ee0c710a2)
![Screenshot 2024-03-08 123700](https://github.com/activist-org/activist/assets/48526455/fd91f267-7c44-4dac-b51d-4d882782fd82)

**Comment by andrewtavis** [comment]
Hey @lucianmurmurache! Thanks for all of these :) Quick note on the relative and sticky, there was something that this was breaking, which is why they're both there, but I can take a look at it again as maybe it just wasn't applied properly (I get that it can't be both, but without both the fade out and in was breaking??). The others are all things I've been seeing and was planning on making issues for. Appreciate the help so much! 😊

**Comment by andrewtavis** [comment]
Closed via #753 😊 Thanks for the changes here, @lucianmurmurache! 🙌
